### PR TITLE
Include sample schedule

### PR DESCRIPTION
**Pull request by angela-li**
Added so instructors can have a sense of how to structure a workshop

### CODE REVIEW

**Comment by angela-li** [comment]
Not sure if I should include this on an Instructor Notes pages instead?

**Comment by ErinBecker** [comment]
I like adding this to the overview page @angela-li. My only concern is that we almost never have time to do SQL (based on timing for this and comparing it to the Ecology workshop where it was forked from). I'm worried that Instructors will rush through the programming language to try to squeeze in SQL.

**Comment by angela-li** [comment]
Hm, that's a good point. I'll be teaching this full workshop in a week, so we'll see how the timing feels on it. Might edit this later depending on how that goes.

**Comment by likeajumprope** [comment]
Hi is this PR still up to date?

**Comment by bencomp** [comment]
I don't think it is, no. GitHub already says that merge conflicts need to be solved before it can be merged. The proposed sample schedule is very optimistic compared to my experience.

A sample schedule may be useful, as currently the generic workshop schedule is empty.

**Comment by likeajumprope** [comment]
Maybe we should close this PR then and open an issue for an updated sample schedule?

**Comment by bencomp** [comment]
See #55 for the follow-up issue. Maybe we can still fix this, @angela-li and @ErinBecker? Or are you okay with closing this PR?

**Comment by ErinBecker** [comment]
Thanks @bencomp for the updated PR. Closing this.

**Pull request closed without merging**
